POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Nada",
    "description":"Nada",
    "duration": 3600
}

###

GET http://localhost:3333/videos?search=Nada

###

PUT http://localhost:3333/videos/6a6d6537-0b11-4285-959a-0c31c7277df3
Content-Type: application/json

{
    "title": "QWEQEQEQWEQ",
    "description":"QWEQWEQWEQWEQWE",
    "duration": 1800
}

###

DELETE http://localhost:3333/videos/5cd77f4c-4966-4148-bbd3-3ee5dc7654b5